-- ============================================================================
-- WordPress Database Schema
-- ============================================================================
-- Creates a minimal WordPress database structure for learning SQL tuning
-- Safe to run multiple times (uses IF NOT EXISTS)
-- Target: PostgreSQL, MySQL, Azure SQL compatible
--
-- Estimated execution time: <1 second
-- Resulting schema size: ~10MB with sample data (generated by setup_test_data.sql)
-- ============================================================================

-- Create tables (WordPress core + minimal essential tables)

CREATE TABLE IF NOT EXISTS wp_posts (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_author BIGINT UNSIGNED NOT NULL DEFAULT 0,
  post_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_date_gmt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_content LONGTEXT NOT NULL DEFAULT '',
  post_title TEXT NOT NULL DEFAULT '',
  post_excerpt TEXT NOT NULL DEFAULT '',
  post_status VARCHAR(20) NOT NULL DEFAULT 'draft',
  comment_status VARCHAR(20) NOT NULL DEFAULT 'open',
  ping_status VARCHAR(20) NOT NULL DEFAULT 'open',
  post_password VARCHAR(255) NOT NULL DEFAULT '',
  post_name VARCHAR(200) NOT NULL DEFAULT '',
  to_ping TEXT NOT NULL DEFAULT '',
  pinged TEXT NOT NULL DEFAULT '',
  post_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_modified_gmt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_content_filtered LONGTEXT NOT NULL DEFAULT '',
  post_parent BIGINT UNSIGNED NOT NULL DEFAULT 0,
  guid VARCHAR(255) NOT NULL DEFAULT '',
  menu_order INT NOT NULL DEFAULT 0,
  post_type VARCHAR(20) NOT NULL DEFAULT 'post',
  post_mime_type VARCHAR(100) NOT NULL DEFAULT '',
  comment_count BIGINT NOT NULL DEFAULT 0,
  KEY post_author (post_author),
  KEY post_status_post_type (post_status, post_type),
  KEY post_parent (post_parent),
  KEY post_type (post_type),
  KEY post_name (post_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Post metadata (highest volume table in typical WordPress)
CREATE TABLE IF NOT EXISTS wp_postmeta (
  meta_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  meta_key VARCHAR(255),
  meta_value LONGTEXT,
  KEY meta_key (meta_key(191)),
  KEY post_id (post_id)
  -- NOTE: Intentionally NOT adding compound index (post_id, meta_key) yet
  -- This is the primary optimization you'll do in exercises!
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Options (site configuration)
CREATE TABLE IF NOT EXISTS wp_options (
  option_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  option_name VARCHAR(191) NOT NULL UNIQUE,
  option_value LONGTEXT NOT NULL DEFAULT '',
  autoload VARCHAR(20) NOT NULL DEFAULT 'yes',
  KEY autoload (autoload)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Comments
CREATE TABLE IF NOT EXISTS wp_comments (
  comment_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  comment_post_ID BIGINT UNSIGNED NOT NULL DEFAULT 0,
  comment_author TEXT NOT NULL DEFAULT '',
  comment_author_email VARCHAR(100) NOT NULL DEFAULT '',
  comment_author_URL VARCHAR(200) NOT NULL DEFAULT '',
  comment_author_IP VARCHAR(100) NOT NULL DEFAULT '',
  comment_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comment_date_gmt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comment_content TEXT NOT NULL DEFAULT '',
  comment_karma INT NOT NULL DEFAULT 0,
  comment_approved VARCHAR(20) NOT NULL DEFAULT '1',
  comment_agent VARCHAR(255) NOT NULL DEFAULT '',
  comment_type VARCHAR(20) NOT NULL DEFAULT '',
  comment_parent BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  KEY comment_post_ID (comment_post_ID),
  KEY comment_post_ID_approved (comment_post_ID, comment_approved),
  KEY comment_approved (comment_approved)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users (FIXED: Removed duplicate KEY user_login and KEY user_email)
CREATE TABLE IF NOT EXISTS wp_users (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_login VARCHAR(60) NOT NULL UNIQUE,
  user_pass VARCHAR(255) NOT NULL DEFAULT '',
  user_nicename VARCHAR(50) NOT NULL DEFAULT '',
  KEY user_nicename (user_nicename),
  user_email VARCHAR(100) NOT NULL UNIQUE,
  user_url VARCHAR(100) NOT NULL DEFAULT '',
  user_registered DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_activation_key VARCHAR(255) NOT NULL DEFAULT '',
  user_status INT NOT NULL DEFAULT 0,
  display_name VARCHAR(250) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User metadata
CREATE TABLE IF NOT EXISTS wp_usermeta (
  umeta_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  meta_key VARCHAR(255),
  meta_value LONGTEXT,
  KEY user_id (user_id),
  KEY meta_key (meta_key(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Taxonomies (categories, tags) (FIXED: Removed duplicate KEY slug)
CREATE TABLE IF NOT EXISTS wp_terms (
  term_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL DEFAULT '',
  KEY name (name),
  slug VARCHAR(200) NOT NULL UNIQUE,
  term_group BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Taxonomy taxonomy (post_tag, category, etc.)
CREATE TABLE IF NOT EXISTS wp_term_taxonomy (
  term_taxonomy_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  term_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  taxonomy VARCHAR(32) NOT NULL DEFAULT '',
  description LONGTEXT NOT NULL DEFAULT '',
  parent BIGINT UNSIGNED NOT NULL DEFAULT 0,
  count BIGINT NOT NULL DEFAULT 0,
  KEY term_id (term_id),
  KEY taxonomy (taxonomy),
  KEY parent (parent),
  UNIQUE KEY term_id_taxonomy (term_id, taxonomy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Post to taxonomy relationship
CREATE TABLE IF NOT EXISTS wp_term_relationships (
  object_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  term_taxonomy_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  term_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (object_id, term_taxonomy_id),
  KEY term_taxonomy_id (term_taxonomy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- SUMMARY
-- ============================================================================
-- Tables created: 9 (wp_posts, wp_postmeta, wp_options, wp_comments, wp_users,
--                    wp_usermeta, wp_terms, wp_term_taxonomy, wp_term_relationships)
-- Schema size: <1MB
-- Estimated test data size: 10-50MB (after loading sample data)
--
-- Next steps:
-- 1. Run: scripts/setup_test_data.sql (populate with realistic data)
-- 2. Run: EXPLAIN queries in exercises/day1_wordpress_audit/ to see full table scans
-- 3. Optimize: Add missing indexes (the main learning exercise)
-- ============================================================================

